---
output: github_document
---

<!-- README-Inputs.md is generated from README-Inputs.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### Description of Input Files

This folder contains the formatted data to run the [CIBW_ME_Model-ms_code.R](scripts/CIBW_ME_Model-ms_code.R) multievent mark-recapture model as well as the starting latent matrix required by JAGS. See manuscript for detailed description of data.

* [ms_SH_data.csv](inputs/ms_SH_data.csv): Formatted (.csv) data to run the multievent mark-recapture model
* [start_mat-ms_SH_data.csv](inputs/start_mat-ms_SH_data.csv): Formatted (.csv) "starting" latent matrix corresponding to the ms_SH_data.csv file

The starting latent matrix is one possible iteration of the true states described by the observed sighting history data. JAGS requires this starting matrix in order to run the model. Other starting latent matrices could be used as long as the true states in the matrix could give rise to the observed data.
